baseURL = 'https://www.noe.backert.fr/'
languageCode = 'en-us'
title = 'Noé Backert | Blog'
theme = 'PaperMod'
enableEmoji = true

[params.meta]
  description = "Noé Backert's personal blog, featuring CTF writeups, projects, and a resume."
  keywords = ["CTF", "Writeups", "Projects", "Resume", "Blog"]
  author = "Noé Backert"

[params.assets]
  favicon = "/img/favicon.ico"


[params]
  author = "Noé Backert"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  mainSections = ["ctf", "projects"]  
  customCSS = ["css/custom.css"]
  # Custom description truncation length for home page
  homeDescriptionLength = 200
  # Enable code copy buttons
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    name = "CTF Writeups"
    url = "/ctf/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/Projects/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

# Markup configuration to allow raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    noClasses = false

# Suppress the raw HTML warnings  
ignoreLogs = ['warning-goldmark-raw-html']

